const constant = {};
constant.APP_SET_ALERT_MESSAGE = "APP_SET_ALERT_MESSAGE";
constant.APP_CLOSE_ALERT_MESSAGE = "APP_CLOSE_ALERT_MESSAGE";
constant.SET_LOADING_STATUS = "SET_LOADING_STATUS";

constant.SET_ADMIN_LOGGED_IN = "SET_ADMIN_LOGGED_IN";
// Food Showing and update delete by amdin
constant.FETCH_FOODS_DATA_SUCCESS = "FETCH_FOODS_DATA_SUCCESS";
constant.FETCH_SINGLE_FOOD_DATA_SUCCESS = "FETCH_SINGLE_FOOD_DATA_SUCCESS";
constant.ADD_FOOD_SUCCESS = "ADD_FOOD_SUCCESS";
constant.DELETE_FOOD_SUCCESS = "DELETE_FOOD_SUCCESS";
constant.UPDATE_FOOD_SUCCESS = "UPDATE_FOOD_SUCCESS";

// Order Food By User
constant.USER_CHANGE_FOOD_QUANTITY = "USER_CHANGE_FOOD_QUANTITY";
constant.USER_ORDER_CONFIRM_SUCCESS = "USER_ORDER_CONFIRM_SUCCESS";
constant.FETCH_USER_ORDERS_SUCCESS = "FETCH_USER_ORDERS_SUCCESS";
constant.ORDER_DELETE_SUCCESS = "ORDER_DELETE_SUCCESS";
constant.FETCH_ALL_ORDERS_SUCCESS = "FETCH_ALL_ORDERS_SUCCESS";

constant.CHANGE_ORDER_STATUS_SUCCESS = "CHANGE_ORDER_STATUS_SUCCESS";
export default constant;
